version: '3.7'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'mmdb'
      MYSQL_ROOT_PASSWORD: 'MyNewPass4!'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PYTHONPATH: '/app/src/'
    ports:
      - "80:80"
    depends_on:
      - db
