# Generated by Django 2.2.1 on 2019-12-26 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cell_phone', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=20)),
                ('town', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=100)),
                ('tag', models.CharField(choices=[('home', '家'), ('company', '公司'), ('school', '学校')], max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('last_use_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
