# Generated by Django 2.2.1 on 2019-12-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='last_use_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
