# Generated by Django 2.2.1 on 2019-12-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191227_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='tag',
            field=models.CharField(blank=True, choices=[('home', '家'), ('company', '公司'), ('school', '学校')], max_length=10, null=True),
        ),
    ]
