# Generated by Django 2.2.1 on 2019-12-30 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0011_auto_20191226_1251'),
        ('order', '0004_coupon_receivecoupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.AlterModelOptions(
            name='receivecoupon',
            options={'verbose_name': 'ReceiveCoupon', 'verbose_name_plural': 'ReceiveCoupons'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'ShippingAddress', 'verbose_name_plural': 'ShippingAddresses'},
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unpaid', '待付款'), ('paid', '已付款'), ('shipped', '已发货'), ('received', '已收货')], max_length=10)),
                ('products_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport_costs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.CharField(choices=[('individual', '个人'), ('company ', '公司')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Coupon')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.ShippingAddress')),
                ('skus', models.ManyToManyField(to='product.Sku')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
