# Generated by Django 2.2.1 on 2019-12-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20191230_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.CharField(choices=[('individual', '个人'), ('company', '公司')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', '待付款'), ('paid', '已付款'), ('shipped', '已发货'), ('received', '已收货'), ('refunding', '申请退款中'), ('refunded', '退款完成')], default='unpaid', max_length=10),
        ),
    ]
