# Generated by Django 2.2.1 on 2019-12-31 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191230_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('wechat', '微信'), ('alipay', '支付宝')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pay_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pay_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='remark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', '待付款'), ('paid', '已付款'), ('shipping', '发货'), ('received', '已收货'), ('refund', '退款')], default='unpaid', max_length=10),
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_no', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', '打包中'), ('shipped', '已发货'), ('received', '已收货')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='order.Review')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_no', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('applied', '申请退款'), ('processing', '退款中'), ('success', '退款成功'), ('fail', '退款失败')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='order.Review')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='order.Review'),
        ),
    ]
