# Generated by Django 2.2.1 on 2020-01-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20191231_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_time',
            field=models.DateTimeField(null=True),
        ),
    ]
