# Generated by Django 2.2.1 on 2020-01-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='skus',
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(to='order.OrderItem'),
        ),
    ]
