# Generated by Django 2.2.1 on 2020-01-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20200101_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(to='order.OrderItem'),
        ),
    ]
