# Generated by Django 2.2.1 on 2020-01-01 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20200101_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Sku'),
        ),
    ]
