# Generated by Django 2.2.1 on 2020-01-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20200101_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(blank=True, choices=[('wechat', '微信'), ('alipay', '支付宝')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.Review'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', '待付款'), ('paid', '已付款'), ('shipping', '待收货'), ('received', '待评价'), ('reviewed', '已评价'), ('refund', '退款')], default='unpaid', max_length=10),
        ),
    ]
