# Generated by Django 2.2.1 on 2020-01-02 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20200101_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='closed',
        ),
    ]
