# Generated by Django 2.2.1 on 2020-01-02 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_remove_order_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefundReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='review',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='review',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='review',
        ),
        migrations.AddField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='shippingreview',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Shipping'),
        ),
        migrations.AddField(
            model_name='refundreview',
            name='refund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Refund'),
        ),
        migrations.AddField(
            model_name='orderreview',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
    ]
