# Generated by Django 2.2.1 on 2020-01-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20200102_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderreview',
            options={'verbose_name': 'OrderReview', 'verbose_name_plural': 'OrderReviews'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'verbose_name': 'Refund', 'verbose_name_plural': 'Refunds'},
        ),
        migrations.AlterModelOptions(
            name='refundreview',
            options={'verbose_name': 'RefundReview', 'verbose_name_plural': 'RefundReviews'},
        ),
        migrations.AlterModelOptions(
            name='shipping',
            options={'verbose_name': 'Shipping', 'verbose_name_plural': 'Shippings'},
        ),
        migrations.AlterModelOptions(
            name='shippingreview',
            options={'verbose_name': 'ShippingReview', 'verbose_name_plural': 'ShippingReviews'},
        ),
        migrations.AddField(
            model_name='refund',
            name='reason',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
