# Generated by Django 2.2.12 on 2020-04-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20200215_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': '优惠券', 'verbose_name_plural': '优惠券'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': '订单里的商品', 'verbose_name_plural': '订单里的商品'},
        ),
        migrations.AlterModelOptions(
            name='orderreview',
            options={'verbose_name': '订单评价', 'verbose_name_plural': '订单评价'},
        ),
        migrations.AlterModelOptions(
            name='receivecoupon',
            options={'verbose_name': '用户领取的优惠券', 'verbose_name_plural': '用户领取的优惠券'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'verbose_name': '退款信息', 'verbose_name_plural': '退款信息'},
        ),
        migrations.AlterModelOptions(
            name='refundreview',
            options={'verbose_name': '退款评价', 'verbose_name_plural': '退款评价'},
        ),
        migrations.AlterModelOptions(
            name='shipping',
            options={'verbose_name': '物流信息', 'verbose_name_plural': '物流信息'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': '收货地址', 'verbose_name_plural': '收货地址'},
        ),
        migrations.AlterModelOptions(
            name='shippingreview',
            options={'verbose_name': '物流评价', 'verbose_name_plural': '物流评价'},
        ),
    ]
