# Generated by Django 2.2.1 on 2019-12-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20191227_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='chosen_price',
        ),
    ]
