# Generated by Django 2.2.1 on 2019-12-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20191227_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.Cart'),
        ),
    ]
