# Generated by Django 2.2.1 on 2020-02-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20191227_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcartitem',
            name='purchase_num',
            field=models.PositiveIntegerField(),
        ),
    ]
