# Generated by Django 2.2.1 on 2020-02-18 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20200215_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcartitem',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Sku'),
        ),
    ]
