# Generated by Django 2.2.1 on 2020-02-19 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200213_1842'),
        ('cart', '0009_auto_20200218_1832'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productcartitem',
            unique_together={('cart', 'sku')},
        ),
    ]
