# Generated by Django 2.2.12 on 2020-04-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20200219_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': '用户的购物车', 'verbose_name_plural': '用户的购物车'},
        ),
        migrations.AlterModelOptions(
            name='productcartitem',
            options={'verbose_name': '加入的购物车商品', 'verbose_name_plural': '加入的购物车商品'},
        ),
    ]
