# Generated by Django 2.2.1 on 2019-12-24 05:08

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(choices=[('recommends', '推荐'), ('cellphone', '手机'), ('Intelligence', '智能'), ('tv', '电视'), ('laptop', '笔记本'), ('appliance', '家电'), ('life', '生活周边')], unique=True)),
                ('active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('desc', models.TextField()),
                ('img_height', models.IntegerField()),
                ('img_width', models.IntegerField()),
                ('cover_img', models.ImageField(height_field='img_height', upload_to=product.models.product_cover_image_upload, width_field='img_width')),
                ('active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(choices=[('new_arrival', '新品发布'), ('crowd_funding', '小米众筹'), ('hot', '热卖中'), ('old_for_new', '以旧换新'), ('seckill', '小米秒杀'), ('group_purchase', '一分拼团')], unique=True)),
                ('img_height', models.IntegerField(blank=True)),
                ('img_width', models.IntegerField(blank=True)),
                ('cover_img', models.ImageField(height_field='img_height', upload_to=product.models.theme_activity_image_upload, width_field='img_width')),
                ('active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('img_height', models.IntegerField()),
                ('img_width', models.IntegerField()),
                ('cover_img', models.ImageField(height_field='img_height', upload_to=product.models.second_category_image_upload, width_field='img_width')),
                ('active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('first_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.FirstCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_height', models.IntegerField(blank=True, null=True)),
                ('img_width', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(height_field='image_height', upload_to=product.models.product_detail_image_upload, width_field='image_width')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_images', to='product.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ThemeActivity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ThemeActivity'),
        ),
        migrations.AddField(
            model_name='product',
            name='first_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.FirstCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='second_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SecondCategory'),
        ),
    ]
