# Generated by Django 2.2.1 on 2019-12-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondcategory',
            name='img_height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='secondcategory',
            name='img_width',
            field=models.IntegerField(blank=True),
        ),
    ]
