# Generated by Django 2.2.1 on 2019-12-25 11:22

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191225_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('carousel', '动态轮播图'), ('pos1', '位置1'), ('pos2', '位置2'), ('pos3', '位置3'), ('pos4', '位置4')], max_length=20)),
                ('link_url', models.CharField(max_length=50)),
                ('image_height', models.IntegerField(blank=True)),
                ('image_width', models.IntegerField(blank=True)),
                ('image', models.ImageField(blank=True, height_field='image_height', null=True, upload_to=product.models.ad_image_upload, width_field='image_width')),
            ],
            options={
                'verbose_name': 'AdProduct',
                'verbose_name_plural': 'AdProducts',
            },
        ),
        migrations.AddField(
            model_name='themeactivity',
            name='link_url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
