# Generated by Django 2.2.1 on 2019-12-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20191225_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeactivity',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
