# Generated by Django 2.2.1 on 2019-12-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20191225_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_width',
            field=models.IntegerField(blank=True),
        ),
    ]
