# Generated by Django 2.2.1 on 2019-12-25 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20191225_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ThemeActivity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ThemeActivity'),
        ),
    ]
