# Generated by Django 2.2.1 on 2019-12-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20191225_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondcategory',
            name='link_url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
