# Generated by Django 2.2.1 on 2019-12-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_secondcategory_link_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondcategory',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
