# Generated by Django 2.2.1 on 2019-12-26 04:44

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_secondcategory_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cover_img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img_width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('img_height', models.IntegerField(blank=True)),
                ('img_width', models.IntegerField(blank=True)),
                ('cover_img', models.ImageField(height_field='img_height', upload_to=product.models.product_cover_image_upload, width_field='img_width')),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inventory', models.IntegerField()),
                ('min_purchase_num', models.IntegerField(default=1)),
                ('max_purchase_num', models.IntegerField(default=9999)),
                ('is_active', models.BooleanField(default=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
