# Generated by Django 2.2.1 on 2019-12-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20191226_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='version',
            field=models.CharField(max_length=50),
        ),
    ]
