# Generated by Django 2.2.1 on 2020-02-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20191226_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ThemeActivity',
            new_name='theme_activity',
        ),
    ]
