# Generated by Django 2.2.1 on 2020-02-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200222_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcarouselimage',
            old_name='post',
            new_name='product',
        ),
    ]
