# Generated by Django 2.2.12 on 2020-04-30 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import upload_file.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('upload_file', models.FileField(upload_to=upload_file.models.file_upload)),
                ('size', models.BigIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户上传的文件',
                'verbose_name_plural': '用户上传的文件',
            },
        ),
    ]
