# Generated by Django 2.2.12 on 2020-04-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20200425_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloginlog',
            name='login_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='login_type',
            field=models.CharField(choices=[('veri_code', '验证码登录'), ('account', '账户登录')], max_length=100),
        ),
    ]
