# Generated by Django 2.2.12 on 2020-04-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20200425_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': '配置', 'verbose_name_plural': '配置'},
        ),
        migrations.AlterModelOptions(
            name='sendcodelog',
            options={'verbose_name': '发送验证码日志', 'verbose_name_plural': '发送验证码日志'},
        ),
        migrations.AlterModelOptions(
            name='userloginlog',
            options={'verbose_name': '用户登录日志', 'verbose_name_plural': '用户登录日志'},
        ),
    ]
