# Generated by Django 2.2.1 on 2019-12-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wechat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '付款成功'), ('fail', '付款失败')], max_length=10)),
                ('order_no', models.CharField(max_length=50)),
            ],
        ),
    ]
