# Generated by Django 2.2.1 on 2020-01-01 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wechat',
            options={'verbose_name': 'Wechat', 'verbose_name_plural': 'Wechats'},
        ),
    ]
