# Generated by Django 2.2.12 on 2020-04-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_auto_20200101_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wechat',
            options={'verbose_name': '微信', 'verbose_name_plural': '微信'},
        ),
    ]
