# Generated by Django 2.2.12 on 2020-04-23 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vue_admin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=20)),
                ('active_index', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='Submenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='vue_admin.Menu')),
            ],
            options={
                'verbose_name': 'Submenu',
                'verbose_name_plural': 'Submenus',
            },
        ),
        migrations.CreateModel(
            name='NavMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_index', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NavMenu',
                'verbose_name_plural': 'NavMenus',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='navMenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='vue_admin.NavMenu'),
        ),
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('width', models.IntegerField(blank=True)),
                ('height', models.IntegerField(blank=True)),
                ('avatar', models.ImageField(height_field='height', upload_to=vue_admin.models.avatar_upload, width_field='width')),
                ('active', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('navMenu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vue_admin.NavMenu')),
            ],
            options={
                'verbose_name': 'AdminInfo',
                'verbose_name_plural': 'AdminInfos',
            },
        ),
    ]
