# Generated by Django 2.2.12 on 2020-04-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vue_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='active_index',
            new_name='sub_active_index',
        ),
    ]
