# Generated by Django 2.2.12 on 2020-04-26 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vue_admin', '0002_auto_20200423_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admininfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='admininfo',
            name='navMenu',
        ),
        migrations.AddField(
            model_name='admininfo',
            name='owner',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
