# Generated by Django 2.2.12 on 2020-04-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_admin', '0003_auto_20200426_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='active_index',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
