# Generated by Django 2.2.12 on 2020-04-26 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vue_admin', '0004_admininfo_active_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='user_set',
            field=models.ManyToManyField(related_name='user_submenus', to=settings.AUTH_USER_MODEL),
        ),
    ]
