# Generated by Django 2.2.12 on 2020-04-26 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vue_admin', '0005_submenu_user_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='navMenu',
        ),
        migrations.AddField(
            model_name='menu',
            name='user_set',
            field=models.ManyToManyField(related_name='user_menus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='NavMenu',
        ),
    ]
