# Generated by Django 2.2.12 on 2020-04-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue_admin', '0007_auto_20200427_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='url',
            field=models.CharField(max_length=50),
        ),
    ]
