version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'mmdb'
      MYSQL_ROOT_PASSWORD: 'MyNewPass4!'
    volumes:
      - "~/data:/var/lib/mysql"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # ports:
      # - '3306:3306'
  cache_db:
    image: redis
  web_frontend:
    build:
      context: ..
      dockerfile: docker/frontend.dockerfile
    ports:
    - "80:80"
  web_backend:
    build:
      context: ..
      dockerfile: docker/backend.dockerfile
    environment:
      PYTHONPATH: '/app/src/'
    volumes:
      - "../log:/app/log"
      # - "../static_in_env:/app/static_in_env/"
    command: ["src/mm/wsgi.py",
              "--https-port", "443",
              "--https-only",
              "--server-name", "itman.icu",
              "--ssl-certificate-file", "./letsencrypt/live/itman.icu/cert.pem",
              "--ssl-certificate-key-file", "./letsencrypt/live/itman.icu/privkey.pem",
              "--ssl-certificate-chain-file", "./letsencrypt/live/itman.icu/fullchain.pem",
              # "--ssl-ca-certificate-file", "./letsencrypt/live/itman.icu/cert.pem",
              # "--ssl-verify-client", "/admin/",
              # "--document-root", "/app/static_in_env/",
              "--url-alias", "/d/", "/app/download/",
              "--port", "8080"]
    ports:
      - "8080:8080"
      - "443:443"
    depends_on:
      - db
      - cache_db
      - web_frontend
