version: '3.7'

services:
  cache_db:
    image: redis:6.0.1
  db:
    image: mysql:5.7.30
    environment:
      MYSQL_DATABASE: 'mmdb'
      MYSQL_ROOT_PASSWORD: 'MyNewPass4!'
    volumes:
      - "~/data:/var/lib/mysql"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  web:
    build:
      context: ..
      dockerfile: docker/backend.dockerfile
    environment:
      PYTHONPATH: '/app/src/'
    volumes:
      - "../log:/app/log"
    command: ["src/mm/wsgi.py",
              "--port", "8080"]
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache_db
